/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as TenantSlugIndexRouteImport } from './routes/$tenantSlug/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppMeetingTypesRouteImport } from './routes/app/meeting-types'
import { Route as AppAvailabilityRouteImport } from './routes/app/availability'
import { Route as TenantSlugMeetingTypeIndexRouteImport } from './routes/$tenantSlug/$meetingType/index'
import { Route as BookingIdCancelRouteImport } from './routes/booking/$id/cancel'
import { Route as TenantSlugMeetingTypeSuccessIndexRouteImport } from './routes/$tenantSlug/$meetingType/success/index'
import { Route as TenantSlugMeetingTypeFailedIndexRouteImport } from './routes/$tenantSlug/$meetingType/failed/index'
import { Route as TenantSlugMeetingTypeBookIndexRouteImport } from './routes/$tenantSlug/$meetingType/book/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const TenantSlugIndexRoute = TenantSlugIndexRouteImport.update({
  id: '/$tenantSlug/',
  path: '/$tenantSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMeetingTypesRoute = AppMeetingTypesRouteImport.update({
  id: '/meeting-types',
  path: '/meeting-types',
  getParentRoute: () => AppRoute,
} as any)
const AppAvailabilityRoute = AppAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AppRoute,
} as any)
const TenantSlugMeetingTypeIndexRoute =
  TenantSlugMeetingTypeIndexRouteImport.update({
    id: '/$tenantSlug/$meetingType/',
    path: '/$tenantSlug/$meetingType/',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookingIdCancelRoute = BookingIdCancelRouteImport.update({
  id: '/booking/$id/cancel',
  path: '/booking/$id/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSlugMeetingTypeSuccessIndexRoute =
  TenantSlugMeetingTypeSuccessIndexRouteImport.update({
    id: '/$tenantSlug/$meetingType/success/',
    path: '/$tenantSlug/$meetingType/success/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TenantSlugMeetingTypeFailedIndexRoute =
  TenantSlugMeetingTypeFailedIndexRouteImport.update({
    id: '/$tenantSlug/$meetingType/failed/',
    path: '/$tenantSlug/$meetingType/failed/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TenantSlugMeetingTypeBookIndexRoute =
  TenantSlugMeetingTypeBookIndexRouteImport.update({
    id: '/$tenantSlug/$meetingType/book/',
    path: '/$tenantSlug/$meetingType/book/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/availability': typeof AppAvailabilityRoute
  '/app/meeting-types': typeof AppMeetingTypesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/$tenantSlug': typeof TenantSlugIndexRoute
  '/app/': typeof AppIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/booking/$id/cancel': typeof BookingIdCancelRoute
  '/$tenantSlug/$meetingType': typeof TenantSlugMeetingTypeIndexRoute
  '/$tenantSlug/$meetingType/book': typeof TenantSlugMeetingTypeBookIndexRoute
  '/$tenantSlug/$meetingType/failed': typeof TenantSlugMeetingTypeFailedIndexRoute
  '/$tenantSlug/$meetingType/success': typeof TenantSlugMeetingTypeSuccessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/availability': typeof AppAvailabilityRoute
  '/app/meeting-types': typeof AppMeetingTypesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/$tenantSlug': typeof TenantSlugIndexRoute
  '/app': typeof AppIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/booking/$id/cancel': typeof BookingIdCancelRoute
  '/$tenantSlug/$meetingType': typeof TenantSlugMeetingTypeIndexRoute
  '/$tenantSlug/$meetingType/book': typeof TenantSlugMeetingTypeBookIndexRoute
  '/$tenantSlug/$meetingType/failed': typeof TenantSlugMeetingTypeFailedIndexRoute
  '/$tenantSlug/$meetingType/success': typeof TenantSlugMeetingTypeSuccessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/availability': typeof AppAvailabilityRoute
  '/app/meeting-types': typeof AppMeetingTypesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/$tenantSlug/': typeof TenantSlugIndexRoute
  '/app/': typeof AppIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/booking/$id/cancel': typeof BookingIdCancelRoute
  '/$tenantSlug/$meetingType/': typeof TenantSlugMeetingTypeIndexRoute
  '/$tenantSlug/$meetingType/book/': typeof TenantSlugMeetingTypeBookIndexRoute
  '/$tenantSlug/$meetingType/failed/': typeof TenantSlugMeetingTypeFailedIndexRoute
  '/$tenantSlug/$meetingType/success/': typeof TenantSlugMeetingTypeSuccessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/privacy'
    | '/terms'
    | '/app/availability'
    | '/app/meeting-types'
    | '/auth/login'
    | '/auth/register'
    | '/$tenantSlug'
    | '/app/'
    | '/dashboard'
    | '/booking/$id/cancel'
    | '/$tenantSlug/$meetingType'
    | '/$tenantSlug/$meetingType/book'
    | '/$tenantSlug/$meetingType/failed'
    | '/$tenantSlug/$meetingType/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/app/availability'
    | '/app/meeting-types'
    | '/auth/login'
    | '/auth/register'
    | '/$tenantSlug'
    | '/app'
    | '/dashboard'
    | '/booking/$id/cancel'
    | '/$tenantSlug/$meetingType'
    | '/$tenantSlug/$meetingType/book'
    | '/$tenantSlug/$meetingType/failed'
    | '/$tenantSlug/$meetingType/success'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/privacy'
    | '/terms'
    | '/app/availability'
    | '/app/meeting-types'
    | '/auth/login'
    | '/auth/register'
    | '/$tenantSlug/'
    | '/app/'
    | '/dashboard/'
    | '/booking/$id/cancel'
    | '/$tenantSlug/$meetingType/'
    | '/$tenantSlug/$meetingType/book/'
    | '/$tenantSlug/$meetingType/failed/'
    | '/$tenantSlug/$meetingType/success/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  TenantSlugIndexRoute: typeof TenantSlugIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  BookingIdCancelRoute: typeof BookingIdCancelRoute
  TenantSlugMeetingTypeIndexRoute: typeof TenantSlugMeetingTypeIndexRoute
  TenantSlugMeetingTypeBookIndexRoute: typeof TenantSlugMeetingTypeBookIndexRoute
  TenantSlugMeetingTypeFailedIndexRoute: typeof TenantSlugMeetingTypeFailedIndexRoute
  TenantSlugMeetingTypeSuccessIndexRoute: typeof TenantSlugMeetingTypeSuccessIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/$tenantSlug/': {
      id: '/$tenantSlug/'
      path: '/$tenantSlug'
      fullPath: '/$tenantSlug'
      preLoaderRoute: typeof TenantSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/meeting-types': {
      id: '/app/meeting-types'
      path: '/meeting-types'
      fullPath: '/app/meeting-types'
      preLoaderRoute: typeof AppMeetingTypesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/availability': {
      id: '/app/availability'
      path: '/availability'
      fullPath: '/app/availability'
      preLoaderRoute: typeof AppAvailabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/$tenantSlug/$meetingType/': {
      id: '/$tenantSlug/$meetingType/'
      path: '/$tenantSlug/$meetingType'
      fullPath: '/$tenantSlug/$meetingType'
      preLoaderRoute: typeof TenantSlugMeetingTypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id/cancel': {
      id: '/booking/$id/cancel'
      path: '/booking/$id/cancel'
      fullPath: '/booking/$id/cancel'
      preLoaderRoute: typeof BookingIdCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantSlug/$meetingType/success/': {
      id: '/$tenantSlug/$meetingType/success/'
      path: '/$tenantSlug/$meetingType/success'
      fullPath: '/$tenantSlug/$meetingType/success'
      preLoaderRoute: typeof TenantSlugMeetingTypeSuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantSlug/$meetingType/failed/': {
      id: '/$tenantSlug/$meetingType/failed/'
      path: '/$tenantSlug/$meetingType/failed'
      fullPath: '/$tenantSlug/$meetingType/failed'
      preLoaderRoute: typeof TenantSlugMeetingTypeFailedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantSlug/$meetingType/book/': {
      id: '/$tenantSlug/$meetingType/book/'
      path: '/$tenantSlug/$meetingType/book'
      fullPath: '/$tenantSlug/$meetingType/book'
      preLoaderRoute: typeof TenantSlugMeetingTypeBookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAvailabilityRoute: typeof AppAvailabilityRoute
  AppMeetingTypesRoute: typeof AppMeetingTypesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAvailabilityRoute: AppAvailabilityRoute,
  AppMeetingTypesRoute: AppMeetingTypesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  TenantSlugIndexRoute: TenantSlugIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  BookingIdCancelRoute: BookingIdCancelRoute,
  TenantSlugMeetingTypeIndexRoute: TenantSlugMeetingTypeIndexRoute,
  TenantSlugMeetingTypeBookIndexRoute: TenantSlugMeetingTypeBookIndexRoute,
  TenantSlugMeetingTypeFailedIndexRoute: TenantSlugMeetingTypeFailedIndexRoute,
  TenantSlugMeetingTypeSuccessIndexRoute:
    TenantSlugMeetingTypeSuccessIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
